# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

#pool:
#  vmImage: ubuntu-latest

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo Hello world 2 
  displayName: 'Run a multi-line script'
  
- script: |
    echo Bye
  displayName: 'Bye Script'    
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: AzureCLI@2
  displayName: "Login to Azure"
  inputs:
    azureSubscription: azure_connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging in with Service Principal..."
      az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
      az account set --subscription $(AZURE_SUBSCRIPTION_ID)

- task: TerraformTaskV2@2
  displayName: " Terrafrom Init"
  inputs:
    command: init
    provider: azurerm
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: azure_connection
    backendAzureRmResourceGroupName: 'tfstate-tfdemo-rg'
    backendAzureRmStorageAccountName: 'tfstatedemostg1234'
    backendAzureRmContainerName: 'terraformstatecontainer'
    backendAzureRmKey: 'terraform.tfstate'
    commandOptions: '-lock=false'
    
- task: TerraformTaskV3@3
  displayName: " Terrafrom Plan"  
  inputs:
    command: plan
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: azure_connection

- task: TerraformTaskV3@3
  displayName: " Terraform Apply"  
  condition: false
  inputs:
    command: apply
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: azure_connection
    
- task: TerraformTaskV3@3
  displayName: "Terrafrom Destroy"
  #condition: false
  inputs:
    command: destroy
    environmentServiceNameAzureRM: azure_connection
    workingDirectory: '$(System.DefaultWorkingDirectory)'







    
    
    
    
      
      
       
        

    
    

    
