trigger:
- main 

variables:
  serviceConnection: 'azure_connection'
pool:
  vmImage: ubuntu-latest
  
steps:
  # Step 1: Install Terraform
   - script: |
       sudo apt-get update && sudo apt-get install -y software-properties-common
       sudo apt-add-repository --yes --update ppa:ansible/ansible
       sudo apt-get install ansible -y

       # Install Terraform
       wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
       unzip terraform_1.0.11_linux_amd64.zip
       sudo mv terraform /usr/local/bin/

        # Install Azure CLI
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
     displayName: 'Install Terraform and Azure CLI'

   - checkout: self
   - task: TerraformTaskV4@4
     inputs:
       provider: 'azurerm'
       command: 'init'
       backendServiceArm: 'azure_connection'       
       workingDirectory: '$(System.DefaultWorkingDirectory)'
     displayName: 'Terraform Init'

 